services:
  db:
    image: postgres:16.1
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      -POSTGRES_DB=shareit
      -POSTGRES_USER=dbuser
      -POSTGRES_PASSWORD=12345
    helthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGTRES_USER
      timeout: 5s
      interval: 5s
      retries: 10